name: Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore ./src/Resume.Test/Resume.Test.csproj
      - name: Run tests
        run: dotnet test ./src/Resume.Test/Resume.Test.csproj --no-restore --verbosity normal